package rusystem;

public enum ManagedRuEvent {
    SETUP,
    ACTIVATE,
    DEACTIVATE,
    RELEASE,
    SETUP_CARRIER,
    SIGNAL_SCALING,
    MODIFY_CARRIER,
    REMOVE_CARRIER,
    SELF_DIAGNOSTICS,
    REMOVE_ALL_CARRIERS,
    SET_ALARM_STATUS,
    ACKNOWLEDGE_ALARM,
    POST_ACTIVATION
}