package common;

public enum MenuOption
{
  COMMISSION_RU,
  DECOMMISSION_RU,
  ADD_RADIO_UNIT,
  REMOVE_RADIO_UNIT,
  SETUP_RU,
  RELEASE_RU,
  ACTIVATE_RU,
  DEACTIVATE_RU,
  SETUP_CARRIER_ON_RU,
  MODIFY_CARRIER_ON_RU,
  REMOVE_CARRIER_ON_RU,
  REMOVE_ALL_CARRIERS_ON_RU,
  SIGNAL_SCALING_ON_RU,
  POST_ACTIVATION,
  PERFORM_SELF_DIAGNOSTICS,
  LIST_NETWORK_INVENTORY,
  LIST_RUS_BY_STNADARD,
  LIST_RUS_BY_STATE,
  LIST_RUS_BY_BAND,
  LIST_RADIO_UNIT_DETAILS,
  SET_ALARM_ON_RU,
  GET_NETWORK_ALARMS,
  ACKNOWLEDGE_ALARM
}